name: Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - uses: samemrecebi/ci-carbon-tracker/start@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Build SDist
        run: uv build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

      - uses: samemrecebi/ci-carbon-tracker/stop@v1
        if: always()
        with:
          pr-comment: "true"

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            macos-15-intel,
            macos-26,
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - uses: samemrecebi/ci-carbon-tracker/start@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        with:
          extras: "uv"

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

      - uses: samemrecebi/ci-carbon-tracker/stop@v1
        if: always()
        with:
          pr-comment: "true"
